name: Terraform

on:
  push:
    branches:
      - main

jobs:
  build:                               # Correctly aligns the job name
    runs-on: ubuntu-20.04             # "tflint" was mistakenly under "build", fixed it
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest

      - name: Run TFLint
        run: tflint --chdir=aws -f json > tflint-output.json
        continue-on-error: true

      - name: Upload TFLint Output
        uses: actions/upload-artifact@v2
        with:
          name: TFLint
          path: tflint-output.json
        if: always()                  # Ensures the artifact is uploaded even if previous steps fail

  test:
    runs-on: ubuntu-20.04
    needs: build                      # Ensures "test" runs only after "build"
    steps:
      - name: Run Test Step
        run: echo "This is a test step"

  integration:
    runs-on: ubuntu-20.04
    needs: test                       # Ensures "integration" runs only after "test"
    steps:
      - name: Run Integration Step
        run: echo "This is an integration step"
      - name: Simulate Failure with Continue-on-error
        run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-20.04
    needs: integration                # Ensures "prod" runs only after "integration"
    steps:
      - name: Deploy Step
        run: echo "This is a deploy step"
